language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
before_install: 
  - chmod +x ./script/cibuild.sh
  - ./script/writeWSDL.sh

script: ./script/cibuild.sh

sudo: false

notifications:
  email: false