language: java
git:
  depth: false
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "oliviercailloux-github"
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

