name: Maven CI workflow
on: push
jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Hello world action step
      uses: './.github/actions/Write WSDL_login.txt'
      id: hello
      with:
        who-to-greet: 'Mona the Octocat'
        
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Write WSDL_login file
      uses: DamianReeves/write-file-action@v1.0
      with: 
        path: 'WSDL_login.txt'
        contents: 'https://$(urlencode "${API_username}")@*'
        write-mode: overwrite
      
    - name: Check content
      run: 'echo "https://$(urlencode "${API_username}")@*"'
      
    - name: Maven
      run: mvn -B verify