name: Maven CI workflow
on: push
jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    environment: API
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
     
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Maven
      env:
        #For mvn generate-sources (WSDL access credentials)
        URL_ENCODED_API_USERNAME: ${{ secrets.URL_ENCODED_API_USERNAME }}
        URL_ENCODED_API_PASSWORD: ${{ secrets.URL_ENCODED_API_PASSWORD }}
        #For mvn test (runtime credentials)
        API_USERNAME: ${{ secrets.API_USERNAME }}
        API_PASSWORD: ${{ secrets.API_PASSWORD }}
      run: mvn -PCI verify
