name: Maven CI workflow
on: push
jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Hello world action step
      uses: './.github/actions/Write WSDL_login.txt'
      env:
        API_username: ${{ secrets.API_username }}
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Check content
      run: 'cat "WSDL_login.txt"'
      
    - name: Maven
      run: mvn -B verify