name: Maven CI workflow
on: push
jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Cache
      uses: actions/cache@v2
      with:
        key: maven-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-cache
        path: ~/.m2/repository
        
    - name: Write WSDL_login file
      uses: DamianReeves/write-file-action
      with: null
      path: WSDL_login.txt
      contents: https://@>
      write-mode: invalid
      
    - name: Maven
      run: mvn -B verify